apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
  namespace: myteam-kondev
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox:latest
      name: lifespan-offensive
  restartPolicy: Always